// <auto-generated />
using System;
using Labb2_LINQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2_LINQ.Migrations
{
    [DbContext(typeof(SkolaDBContext))]
    [Migration("20230419213217_initial Creation")]
    partial class initialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2_LINQ.Models.Elev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlasserId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlasserId");

                    b.ToTable("Elever");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Klass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KlassNamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klasser");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("KlasserId")
                        .HasColumnType("int");

                    b.Property<string>("KursNamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LärarnaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlasserId");

                    b.HasIndex("LärarnaId");

                    b.ToTable("Kurser");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Lärare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lärare");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Elev", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Klass", "Klasser")
                        .WithMany()
                        .HasForeignKey("KlasserId");

                    b.Navigation("Klasser");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Kurs", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Klass", "Klasser")
                        .WithMany("Kurser")
                        .HasForeignKey("KlasserId");

                    b.HasOne("Labb2_LINQ.Models.Lärare", "Lärarna")
                        .WithMany()
                        .HasForeignKey("LärarnaId");

                    b.Navigation("Klasser");

                    b.Navigation("Lärarna");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Klass", b =>
                {
                    b.Navigation("Kurser");
                });
#pragma warning restore 612, 618
        }
    }
}
